kind: ServiceAccount
apiVersion: v1
metadata:
  name: node-label-monitor
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:node-label-monitor
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:node-label-monitor
subjects:
  - kind: ServiceAccount
    name: node-label-monitor
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:node-label-monitor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-label-monitor
  name: node-label-monitor
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: node-label-monitor
  template:
    metadata:
      labels:
        app: node-label-monitor
    spec:
      serviceAccount: node-label-monitor
      containers:
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: adaptant/k8s-node-label-monitor:latest
          name: node-label-monitor
          args:
            # Run in node-local mode
            - "-local"
